### ISSUE TITLE
What to add to APT sources

### ISSUE THREAD

**Issue by slashtechno** [psylinux/GoogleDriveMount#1]
What do I add to `//etc/apt/sources.list` ?
Also can you make an automated setup script for first time install?

**Comment by psylinux** [comment]
@slashtechno you don't need to touch in /etc/apt/sources.list, as described in README just add the PPA using the following command:

sudo add-apt-repository ppa:alessandro-strada/ppa

**Comment by slashtechno** [comment]
> @slashtechno you don't need to touch in /etc/apt/sources.list, as described in README just add the PPA using the following command:
> 
> sudo add-apt-repository ppa:alessandro-strada/ppa

@psylinux The problem could be the fact that I am using a Raspberry Pi. Is this x86 only?
